# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 18:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notes',
            managers=[
                ('notesMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
