# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_note', '0002_auto_20170112_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='notes',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
